/**
 * Multi-format quoted-chain parser.
 *
 * Handles three email chain formats that appear in real corporate threads:
 *
 *  1. Gmail-quoted   — .gmail_attr + blockquote.gmail_quote (DOM-based, locale-independent)
 *  2. Gmail forward  — "---------- Forwarded message ---------" header in text
 *  3. Outlook chain  — "From: / Sent: / To: / Subject:" header blocks in text
 *
 * DEDUPLICATION: Map<senderEmail:bodyHash, Segment>
 *   The same message often appears multiple times (original + inside forward).
 *   Key = normalized-email + hash of first 300 normalized body chars.
 *
 * DATA STRUCTURE: flat sorted list (user's stack/list-by-datetime approach)
 *   All parsed segments go into a Map for O(1) dedup, then sorted ascending
 *   by timestamp. This is the correct structure for a chronological chat view.
 */

import type { ParsedMessage } from '../types';
import { buildSender, htmlToText, generateId } from './scraper-utils';

// ── constants ────────────────────────────────────────────────────────────────

// Gmail's forward separator (English — locale-specific but generated by Gmail)
const GMAIL_FORWARD_RE = /[-─—]{5,}\s*Forwarded message\s*[-─—]{5,}/i;

// Outlook "From: / Sent|Date: / To:" block — anchored to line-start
// Allows 1-3 lines between Sent and To for wrapped recipient lists
const OUTLOOK_SEP_RE =
  /^(?:From|De|Von|Van):\s+(.+?)(?:\n(?:Sent|Date|Envoyé|Gesendet|Verzonden):\s+(.+?))?(?:\n[^\n]+){0,3}\n(?:To|À|An|Aan):/m;

// Legal disclaimer stripping — corporate emails repeat these verbatim in every reply.

// ── segment types ────────────────────────────────────────────────────────────

interface Segment {
  senderEmail: string;
  senderName: string;
  timestamp: string;
  bodyText: string;
  bodyHash: string; // used as dedup key component
  depth: number;
}

// ── normalization & hashing ─────────────────────────────────────────────────

const DISCLAIMER_RE = /\s*(?:this e-?mail and any attachments|this message contains information that is confidential|agreements binding|e-mail transmissions are not secure)[\s\S]{0,3000}$/i;

function stripDisclaimer(text: string): string {
  return text.replace(DISCLAIMER_RE, '').trim();
}

function normalizeBody(text: string): string {
  return text
    .toLowerCase()
    .replace(/\s+/g, ' ')
    // Single regex strips all legal disclaimer variants from the point they appear.
    // Covers: Wickes/Aptean/corporate boilerplate that repeats verbatim in every email.
    .replace(
      /(?:this e-?mail and any attachments|this message contains information that is confidential|agreements binding|e-mail transmissions are not secure)[\s\S]{0,3000}$/i,
      ''
    )
    .trim();
}
function hashBody(text: string): string {
  const normalized = normalizeBody(text);
  const sample = normalized.slice(0, 300);
  let h = 0;
  for (let i = 0; i < sample.length; i++) h = (h * 31 + sample.charCodeAt(i)) | 0;
  return Math.abs(h).toString(36);
}

function dedupKey(email: string, bodyHash: string): string {
  return `${email.toLowerCase().trim()}:${bodyHash}`;
}

// ── sender extraction ────────────────────────────────────────────────────────

function parseSenderFromText(raw: string): { name: string; email: string } {
  // "Name <email>" or "Name (email)" or just "email"
  const angleMatch = raw.match(/^(.+?)\s*<([\w.+\-]+@[\w.\-]+\.[a-zA-Z]{2,})>/);
  if (angleMatch) {
    return { name: angleMatch[1].trim() || angleMatch[2].split('@')[0], email: angleMatch[2].toLowerCase() };
  }
  const emailOnly = raw.match(/[\w.+\-]+@[\w.\-]+\.[a-zA-Z]{2,}/);
  if (emailOnly) {
    return { name: emailOnly[0].split('@')[0], email: emailOnly[0].toLowerCase() };
  }
  return { name: raw.trim() || 'Unknown', email: 'unknown@unknown' };
}

// ── timestamp parsing ────────────────────────────────────────────────────────

function parseTimestampFromText(raw: string, depth: number, anchorTimestamp: string): string {
  // Try explicit date patterns before falling back
  const datePatterns = [
    // "Mon, Apr 6, 2026 at 2:57 PM" (Gmail)
    /(?:Mon|Tue|Wed|Thu|Fri|Sat|Sun),?\s+(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+\d{1,2},\s+\d{4}(?:[\s,]+(?:at\s+)?\d{1,2}:\d{2}\s*(?:AM|PM)?)?/i,
    // "01 May 2026 14:50" or "01 May 2026" (Outlook)
    /\d{1,2}\s+(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+\d{4}(?:\s+\d{1,2}:\d{2})?/i,
    // "2026-04-24 13:20:38" (ISO-like)
    /\d{4}-\d{2}-\d{2}(?:\s+\d{2}:\d{2}:\d{2})?/,
    // "Tue, 5 May 2026, 12:07" (alternate Gmail)
    /\w+,\s+\d{1,2}\s+\w+\s+\d{4},?\s+\d{1,2}:\d{2}/,
  ];

  for (const pattern of datePatterns) {
    const match = raw.match(pattern);
    if (match) {
      try {
        const parsed = new Date(match[0]);
        if (!isNaN(parsed.getTime())) return parsed.toISOString();
      } catch { /* next pattern */ }
    }
  }

  // Anchor-based fallback: estimate before the latest email (stable, not Date.now())
  const anchorMs = new Date(anchorTimestamp).getTime();
  const MS_PER_6H = 6 * 60 * 60 * 1000;
  return new Date(anchorMs - (depth + 1) * MS_PER_6H).toISOString();
}

// ── format parsers ───────────────────────────────────────────────────────────

/**
 * Parse Gmail's "---------- Forwarded message ---------" section.
 * Extracts sender + date from the header, then recursively parses the body.
 */
function parseForwardSection(text: string, depth: number, anchorTimestamp: string, out: Map<string, Segment>): void {
  const fwdIdx = text.search(GMAIL_FORWARD_RE);
  if (fwdIdx === -1) return;

  const afterFwd = text.slice(fwdIdx).replace(GMAIL_FORWARD_RE, '').trim();

  // Extract From / Date from the forward header (next 6 lines at most)
  const headerLines = afterFwd.split('\n').slice(0, 8);
  let senderRaw = '';
  let dateRaw = '';

  for (const line of headerLines) {
    const fromMatch = line.match(/^From:\s+(.+)/i);
    if (fromMatch) senderRaw = fromMatch[1].trim();
    const dateMatch = line.match(/^(?:Date|Sent):\s+(.+)/i);
    if (dateMatch) dateRaw = dateMatch[1].trim();
    if (senderRaw && dateRaw) break;
  }

  // Body = everything after the header block (skip lines until blank line)
  const blankIdx = afterFwd.indexOf('\n\n');
  const body = blankIdx >= 0 ? afterFwd.slice(blankIdx + 2).trim() : afterFwd;

  if (senderRaw && body) {
    const { name, email } = parseSenderFromText(senderRaw);
    const timestamp = parseTimestampFromText(dateRaw, depth, anchorTimestamp);
    const cleanBody = stripDisclaimer(body);
    const hash = hashBody(cleanBody);
    const key = dedupKey(email, hash);
    if (!out.has(key)) {
      out.set(key, { senderEmail: email, senderName: name, timestamp, bodyText: cleanBody, bodyHash: hash, depth });
    }
    // Recursively parse what's inside the forwarded body
    parseOutlookChain(body, depth + 1, anchorTimestamp, out);
    parseForwardSection(body, depth + 1, anchorTimestamp, out);
  }
}

/**
 * Parse Outlook-style "From: / Sent: / To: / Subject:" email chains.
 * Splits the text into segments at each Outlook header block.
 *
 * Scan order: forward sections FIRST, then Outlook within each section.
 * This prevents misattributing Outlook headers inside a forwarded block.
 */
function parseOutlookChain(text: string, depth: number, anchorTimestamp: string, out: Map<string, Segment>): void {
  // Find all Outlook header positions
  const positions: { index: number; senderRaw: string; dateRaw: string }[] = [];

  // Find each "From: ... Sent: ..." block
  let match: RegExpMatchArray | null;
  const scanRe = new RegExp(OUTLOOK_SEP_RE.source, 'mg');
  while ((match = scanRe.exec(text)) !== null) {
    const idx = match.index ?? 0;
    // Validate: "From:" must be at a line start — reject mid-sentence occurrences
    const lineStart = text.lastIndexOf('\n', idx) + 1;
    const prefix = text.slice(lineStart, idx).trim();
    if (prefix.length > 0) continue;

    positions.push({
      index: idx,
      senderRaw: match[1]?.trim() ?? '',
      dateRaw: match[2]?.trim() ?? '',
    });
  }

  if (positions.length === 0) return;

  // Extract body for each segment (text between consecutive headers)
  positions.forEach((pos, i) => {
    const nextPos = positions[i + 1]?.index ?? text.length;
    const fullBlock = text.slice(pos.index, nextPos);

    // Skip the header lines, take the body
    const headerEnd = fullBlock.indexOf('\n\n');
    const rawBody = headerEnd >= 0 ? fullBlock.slice(headerEnd + 2).trim() : '';
    const body = stripDisclaimer(rawBody);
    if (!body || body.length < 20) return; // too short to be meaningful

    const { name, email } = parseSenderFromText(pos.senderRaw);
    const timestamp = parseTimestampFromText(pos.dateRaw, depth + i, anchorTimestamp);
    const hash = hashBody(body);
    const key = dedupKey(email, hash);

    if (!out.has(key)) {
      out.set(key, {
        senderEmail: email,
        senderName: name,
        timestamp,
        bodyText: body,
        bodyHash: hash,
        depth: depth + i,
      });
    }
  });
}

// ── Gmail DOM parser ─────────────────────────────────────────────────────────

function extractSenderFromAttr(attrEl: Element): { name: string; email: string } {
  const anchor = attrEl.querySelector<HTMLAnchorElement>('a[href^="mailto:"]');
  if (anchor) {
    const email = anchor.href.replace('mailto:', '').split('?')[0].trim().toLowerCase();
    const text = anchor.textContent?.trim() ?? '';
    return { name: text.includes('@') ? email.split('@')[0] : text || email.split('@')[0], email };
  }
  const text = attrEl.textContent ?? '';
  const emailMatch = text.match(/[\w.+\-]+@[\w.\-]+\.[a-zA-Z]{2,}/);
  if (emailMatch) {
    const email = emailMatch[0].toLowerCase();
    const name = text.slice(0, text.indexOf(emailMatch[0]))
      .replace(/^.*?\d{1,2}:\d{2}\s*(?:AM|PM)\s*/i, '').replace(/[<,]/g, '').trim()
      || email.split('@')[0];
    return { name, email };
  }
  return { name: 'Unknown', email: 'unknown@unknown' };
}

function parseGmailQuotes(latestBodyEl: Element, depth: number, anchorTimestamp: string, out: Map<string, Segment>): void {
  const attrs = Array.from(latestBodyEl.querySelectorAll<Element>('.gmail_attr'));
  if (attrs.length === 0) return;

  attrs.forEach((attr, i) => {
    let sibling: Element | null = attr.nextElementSibling;
    while (sibling && !sibling.classList.contains('gmail_quote') && !sibling.classList.contains('gmail_attr')) {
      sibling = sibling.nextElementSibling;
    }
    if (!sibling || sibling.classList.contains('gmail_attr')) {
      const prev = attr.previousElementSibling;
      if (prev?.classList.contains('gmail_quote')) sibling = prev;
      else return;
    }

    const { name, email } = extractSenderFromAttr(attr);
    const attrText = attr.textContent ?? '';
    const timestamp = parseTimestampFromText(attrText, depth + i, anchorTimestamp);

    // Extract CLEAN body: remove ALL nested .gmail_attr and .gmail_quote
    const clone = sibling.cloneNode(true) as Element;
    clone.querySelectorAll('.gmail_attr').forEach(el => el.remove());
    clone.querySelectorAll('.gmail_quote').forEach(el => el.remove());
    const bodyText = stripDisclaimer(htmlToText(clone.innerHTML).trim());

    if (!bodyText || bodyText.length < 10) return;

    const hash = hashBody(bodyText);
    const key = dedupKey(email, hash);
    if (!out.has(key)) {
      out.set(key, { senderEmail: email, senderName: name, timestamp, bodyText, bodyHash: hash, depth: depth + i });
    }

    // Recursively parse any forwarded/Outlook content INSIDE this blockquote's clean body
    parseForwardSection(bodyText, depth + i + 1, anchorTimestamp, out);
    parseOutlookChain(bodyText, depth + i + 1, anchorTimestamp, out);
  });
}

// ── main export ───────────────────────────────────────────────────────────────

/**
 * Parses full thread history from the always-expanded latest email.
 * Handles Gmail-quoted, Gmail-forwarded, and Outlook chain formats.
 * Returns messages deduplicated by content and sorted chronologically.
 */
export function parseQuotedChain(
  latestBodyEl: Element,
  currentUserEmail: string,
  threadId: string,
  anchorTimestamp: string,
): ParsedMessage[] {
  // Collect all segments into a dedup Map: senderEmail:bodyHash → Segment
  const segmentMap = new Map<string, Segment>();

  // 1. Gmail-quoted DOM chain (primary, locale-independent)
  parseGmailQuotes(latestBodyEl, 0, anchorTimestamp, segmentMap);

  // 2. Text-based: scan outer body text for forward/Outlook patterns.
  //    Strip .gmail_quote children first to avoid re-scanning content already
  //    processed by parseGmailQuotes (dedup Map prevents data duplication,
  //    but the extra scan is wasteful on long threads).
  const outerClone = latestBodyEl.cloneNode(true) as Element;
  outerClone.querySelectorAll('.gmail_quote').forEach(el => el.remove());
  const outerText = htmlToText(outerClone.innerHTML);
  parseForwardSection(outerText, segmentMap.size, anchorTimestamp, segmentMap);
  parseOutlookChain(outerText, segmentMap.size, anchorTimestamp, segmentMap);

  if (segmentMap.size === 0) return [];

  // 3. Sort all unique segments chronologically (oldest → newest)
  const sorted = Array.from(segmentMap.values()).sort(
    (a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime()
  );

  // 4. Convert to ParsedMessage[], assigning stable IDs
  return sorted.map((seg, i) => ({
    // Stable ID: threadId + dedup key hash (never changes between scrape calls)
    id: generateId(`${threadId}-chain-${seg.senderEmail}-${seg.bodyHash}`, 'chain'),
    sender: buildSender(seg.senderName, seg.senderEmail),
    timestamp: seg.timestamp,
    body: seg.bodyText,
    isCurrentUser: seg.senderEmail === currentUserEmail.toLowerCase(),
    index: -(sorted.length - i),
  }));
}
